import Head from 'next/head';
import MainScene from '../components/MainScene';

export default function Index() {
  return (
    <>
      <Head>
        <title>Augmented Words</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main
        style={{
          height: '100vh',
          width: '100vw',
        }}
      >
        <MainScene />
      </main>
    </>
  );
}
